extends Node

enum Player {
	IDLE_01,
	IDLE_02,
	WALKING,
	RUNNING,
	AXE_360,
	HEAVY_ATTACK_01,
	HEAVY_ATTACK_02,
	HEAVY_ATTACK_03
	HEAVY_ATTACK_JUMP,
	BOW_DRAW,
	BOW_IDLE,
	BOW_AIM_WALK_FORWARD,
	BOW_AIM_WALK_BACK,
	BOW_AIM_WALK_LEFT,
	BOW_AIM_WALK_RIGHT,
	GREATSWORD_HIGH_ATTACK,
	GREATSWORD_JUMP_ATTACK,
	GREATSWORD_SLASH,
	ROLL_01,
	SWORD_ATTACK_01,
	SWORD_ATTACK_02,
	SWORD_SPIN_ATTACK,
	ROLL_TO_RUN
}
